# Generated by Django 4.2 on 2025-12-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ping', models.FloatField(help_text='В миллисекундах')),
                ('download', models.FloatField(help_text='В Мбит/с')),
                ('upload', models.FloatField(help_text='В Мбит/с')),
                ('server', models.CharField(default='local', max_length=200)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
