# Generated by Django 4.2 on 2025-12-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_app', '0003_alter_speedtestresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedtestresult',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='speedtestresult',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='speedtestresult',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedtestresult',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedtestresult',
            name='provider',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
